// <auto-generated />
namespace Minder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class seed1strun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seed1strun));
        
        string IMigrationMetadata.Id
        {
            get { return "201802051741410_seed1strun"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
